lib/mailgun_logger_web/router.ex
defmodule MailgunLoggerWeb.Router do
  use MailgunLoggerWeb, :router
  use Plug.ErrorHandler
  @moduledoc false

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_live_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(Plug.Logger)
  end

  pipeline :ping do
    plug(:accepts, ["html"])
    plug(:put_secure_browser_headers)
  end

  pipeline :auth do
    plug(MailgunLoggerWeb.Plugs.SetupCheck)
    plug(MailgunLoggerWeb.Plugs.Auth)
    plug(MailgunLoggerWeb.Plugs.Permissions)
  end

  # Always except in prod
  if Application.compile_env(:mailgun_logger, :env) == :dev do
    forward("/sent_emails", Bamboo.SentEmailViewerPlug)
  end

  scope "/ping", MailgunLoggerWeb do
    pipe_through([:ping])
    get("/", PingController, :ping)
  end

  scope "/health", MailgunLoggerWeb do
    pipe_through([:ping])
    get("/", PingController, :ping)
  end

  scope "/login", MailgunLoggerWeb do
    pipe_through(:browser)

    get("/", AuthController, :new)
    post("/", AuthController, :create)
  end

  scope "/password-reset", MailgunLoggerWeb do
    pipe_through(:browser)

    scope "/request" do
      get("/", PasswordResetController, :request_new)
      post("/", PasswordResetController, :request_create)
      get("/done", PasswordResetController, :request_done)
    end

    get("/reset/error", PasswordResetController, :reset_error)
    get("/reset/done", PasswordResetController, :reset_done)

    scope "/reset/:reset_token" do
      get("/", PasswordResetController, :reset_new)
      post("/", PasswordResetController, :reset_create)
    end
  end

  scope "/setup", MailgunLoggerWeb do
    pipe_through(:browser)
    get("/", SetupController, :index)
    post("/", SetupController, :create_root)
  end

  scope "/", MailgunLoggerWeb do
    pipe_through([:browser, :auth])

    get("/logout", AuthController, :logout)

    resources("/events", EventController, only: [:index, :show])
    get("/events/:id/stored_message", EventController, :stored_message)
    resources("/accounts", AccountController, except: [:show])
    resources("/users", UserController, except: [:show])

    get("/", PageController, :index)
    post("/trigger-run", PageController, :trigger_run)
    get("/stats", PageController, :stats)
    get("/graphs", PageController, :graphs)
    get("/non-affiliation", PageController, :non_affiliation)
  end
end

lib/mailgun_logger_web/views/layout_view.ex
defmodule MailgunLoggerWeb.LayoutView do
  use MailgunLoggerWeb, :view
  @moduledoc false

  # Door mijn get_role functie te definieren kan ik deze ook gebruiken in de LiveView templates
  alias MailgunLogger.UserRole
  def get_current_user_role(user) do
    UserRole.get_current_user_role(user)
  end
end

lib/mailgun_logger_web/templates/layout/app.html.eex
<%= render_partial("head.html", assigns) %>

  <header id="app-header">
    <div class="top">
      <nav id="main-nav">
        <div id="app-logo">
          <a href="<%= Routes.event_path(@conn, :index) %>">
            <img src="<%= Routes.static_path(@conn, "/assets/images/favicon.png") %>" alt="" id="logo" />
          </a>
        </div>
        <ul>
          <%= if assigns[:current_user] do %>
             <%= if MailgunLogger.Roles.can?(assigns[:current_user], :index, MailgunLogger.Event) do %>
              <li><%= link "Events", to: Routes.event_path(@conn, :index), class: active_link_class(@conn, MailgunLoggerWeb.EventController) %></li>
            <% end %>
            <%= if MailgunLogger.Roles.can?(assigns[:current_user], :view_stats) do %>
              <li><%= link "Stats", to: Routes.page_path(@conn, :stats), class: active_link_class(@conn, MailgunLoggerWeb.PageController, :stats) %></li>
            <% end %>
            <%= if MailgunLogger.Roles.can?(assigns[:current_user], :index, MailgunLogger.Account) do %>
              <li><%= link "Accounts", to: Routes.account_path(@conn, :index), class: active_link_class(@conn, MailgunLoggerWeb.AccountController, :index) %></li>
            <% end %>
            <%= if MailgunLogger.Roles.can?(assigns[:current_user], :index, MailgunLogger.User) do %>
              <li><%= link "Users", to: Routes.user_path(@conn, :index), class: active_link_class(@conn, MailgunLoggerWeb.UserController, :index) %></li>
            <% end %>
            <li style="float: right;"><%= link "Logout", to: Routes.auth_path(@conn, :logout) %></li>
          <% else %>
            <li style="float: right;"><%= link "Login", to: Routes.auth_path(@conn, :new) %></li>
          <% end %>
        </ul>
      </nav>
    </div>
    <div class="subnav">
      <ul>
        <li><%= link "Events", to: Routes.event_path(@conn, :index)  %></li>
        <li>&raquo; Event detail</li>
      </ul>
    </div>
  </header>
  <main>
    <%= @inner_content %>
  </main>

<%= render_partial("foot.html", assigns) %>

lib/mailgun_logger_web/templates/layout/setup.html.eex
<%= render_partial("head.html", assigns) %>
  <%= @inner_content %>
<%= render_partial("foot.html", assigns) %>